# Generated by Django 4.2.2 on 2023-06-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_salary',
            field=models.IntegerField(default=3.25),
        ),
        migrations.AddField(
            model_name='profile',
            name='percent_contribution',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='projected_yearly_salary_increase',
            field=models.FloatField(default=3.25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_age',
            field=models.IntegerField(default=33),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_salary',
            field=models.FloatField(default=87477),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_savings',
            field=models.FloatField(default=10330),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rate_of_return',
            field=models.FloatField(default=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='retirement_age',
            field=models.IntegerField(default=65),
        ),
    ]
