# Generated by Django 4.2.2 on 2023-06-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retirement_calculator', '0002_profile_max_salary_profile_percent_contribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='max_salary',
            field=models.IntegerField(default=143000),
        ),
    ]
